### ISSUE TITLE
Implement functionality to reset passwords

### ISSUE THREAD

**Issue by stefanieschneider** [arthist-lmu/artigo#122]
E.g., see [Stackoverflow](https://stackoverflow.com/questions/71810031/password-reset-django-allauth-and-django-rest-auth).

**Comment by kristbaum** [comment]
For views with dj-rest-auth see [here](https://github.com/iMerica/dj-rest-auth/blob/4b3a4ce846c1fd358dfb1ff9fa3fdc8120d884f9/dj_rest_auth/views.py)
